### ISSUE TITLE
[WIP] Rework login flow

### ISSUE THREAD

**Issue by FabianTerhorst** [Grover-c13/PokeGOAPI-Java#667]
- [x] update the getPlayer api to send the new locale (we could random the locale based on the seed provided on the api constructor, since you merged it) #671
- [x] strip out the login flow from the constructor with a singleton void (like login()) #668
- [x] move all the things from the constructor that affect the login and the signature generation (like timestamps etc) #668
- [ ] remove the requirement to set a http client to the api and to the provider object #672
- [ ] creating a new interface class that will hold callbacks and errors (we need to discuss the way in which we provide the interface. i guess is better if we pass the interface to the new login method and we hold it to interact with the client/app that's using the api)
- [ ] with the new interface class we will be able to do lot of things and rework such as notify login fails, ban status and we can also use it to pass the results of responses)
- [ ] reworking the actual login flow to make it similar to the official client (actually we send only getPlayer and DownloadSettings. We should also send all the other requests that the official client fires at login in order to prevent flags)
- [ ] rework the commit I did 9 days ago to set the tutorial state to legal_screen. We could do this as we did the signature. I will work with the standalone logic by letting the api automatically set a random avatar and nickname based on the given seed. You can work on the extension to allow the manual setup of these things

Use #660 to add suggestions.
